volumes:
  pgdata:

services:
  db:
    image: postgres:16-alpine
    container_name: cheon
    restart: always
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - 5433:5432